name: Cargo Build & Test

on:
  push:
    paths:
    - "src/**"
    - ".github/workflows/ci.yaml"
  pull_request:


env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - stable
        - beta
        - nightly
    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
    - run: cargo build --all-features --verbose
    - run: cargo test --all-features --verbose
    - run: cargo clippy --all-targets --all-features -- -D warnings
    - run: cargo fmt --all --check
    - run: cargo doc --no-deps --verbose
